<?xml version="1.0" encoding="utf-8"?><Database Name="SCM_CangJi" Class="CangJiDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SCM_CangJi;Persist Security Info=True;User ID=sa" SettingsObjectName="SCM_CangJi.DAL.Properties.Settings" SettingsPropertyName="SCM_CangJiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profiles">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_User" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Role" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
    </Type>
  </Table>
  <Table Name="dbo.CurrencyUnits" Member="CurrencyUnits">
    <Type Name="CurrencyUnit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="CurrencyUnit_Product" Member="Products" ThisKey="Id" OtherKey="CurrencyUnitId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phone3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Company_Contact" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTypes" Member="ProductTypes">
    <Type Name="ProductType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductType_ProductType" Member="ProductTypes" ThisKey="Id" OtherKey="ParentId" Type="ProductType" />
      <Association Name="ProductType_Product" Member="Products" ThisKey="Id" OtherKey="ProductTypeId" Type="Product" />
      <Association Name="ProductType_ProductType" Member="ProductType1" ThisKey="ParentId" OtherKey="Id" Type="ProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyAddress" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Company_Contact" Member="Contacts" ThisKey="Id" OtherKey="CompanyId" Type="Contact" />
      <Association Name="Company_Product" Member="Products" ThisKey="Id" OtherKey="CompanyId" Type="Product" />
      <Association Name="Company_DeliverAddress" Member="DeliverAddresses" ThisKey="Id" OtherKey="CompanyId" Type="DeliverAddress" />
      <Association Name="Company_DeliveryOrder" Member="DeliveryOrders" ThisKey="Id" OtherKey="CompanyId" Type="DeliveryOrder" />
      <Association Name="Company_ImportProfile" Member="ImportProfiles" ThisKey="Id" OtherKey="CompanyId" Type="ImportProfile" />
      <Association Name="Company_ProductStorage" Member="ProductStorages" ThisKey="Id" OtherKey="CompanyId" Type="ProductStorage" />
      <Association Name="Company_InputOrder" Member="InputOrders" ThisKey="Id" OtherKey="CompanyId" Type="InputOrder" />
      <Association Name="Company_InputOrderDetail" Member="InputOrderDetails" ThisKey="Id" OtherKey="CompanyId" Type="InputOrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductChName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductEngName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductNumber1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductNumber2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BarCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShelfLife" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreWorningDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecurityCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LayeredCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyUnitId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_DeliveryOrderDetail" Member="DeliveryOrderDetails" ThisKey="Id" OtherKey="ProductId" Type="DeliveryOrderDetail" />
      <Association Name="Product_AssignedDeliveryOrderDetail" Member="AssignedDeliveryOrderDetails" ThisKey="Id" OtherKey="ProductId" Type="AssignedDeliveryOrderDetail" />
      <Association Name="Product_ProductStorage" Member="ProductStorages" ThisKey="Id" OtherKey="ProductId" Type="ProductStorage" />
      <Association Name="Product_InputOrderDetail" Member="InputOrderDetails" ThisKey="Id" OtherKey="ProductId" Type="InputOrderDetail" />
      <Association Name="CurrencyUnit_Product" Member="CurrencyUnit" ThisKey="CurrencyUnitId" OtherKey="Id" Type="CurrencyUnit" IsForeignKey="true" />
      <Association Name="ProductType_Product" Member="ProductType" ThisKey="ProductTypeId" OtherKey="Id" Type="ProductType" IsForeignKey="true" />
      <Association Name="Company_Product" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliverAddresses" Member="DeliverAddresses">
    <Type Name="DeliverAddress">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliverDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DeliverAddress_DeliveryOrder" Member="DeliveryOrders" ThisKey="Id" OtherKey="DeliveryAddressId" Type="DeliveryOrder" />
      <Association Name="Company_DeliverAddress" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryOrders" Member="DeliveryOrders">
    <Type Name="DeliveryOrder">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryOrderNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PreDeliveryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryAddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReachedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Invoice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DeliveryOrder_DeliveryOrderDetail" Member="DeliveryOrderDetails" ThisKey="Id" OtherKey="DeliveryOrderId" Type="DeliveryOrderDetail" />
      <Association Name="DeliveryOrder_AssignedDeliveryOrderDetail" Member="AssignedDeliveryOrderDetails" ThisKey="Id" OtherKey="DeliveryOrderId" Type="AssignedDeliveryOrderDetail" />
      <Association Name="Company_DeliveryOrder" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
      <Association Name="DeliverAddress_DeliveryOrder" Member="DeliverAddress" ThisKey="DeliveryAddressId" OtherKey="Id" Type="DeliverAddress" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderNumbers" Member="OrderNumbers">
    <Type Name="OrderNumber">
      <Column Name="OrderNamrber" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryOrderDetails" Member="DeliveryOrderDetails">
    <Type Name="DeliveryOrderDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeliveryOrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductStorageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LotsNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InputInvoice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DeliveryOrder_DeliveryOrderDetail" Member="DeliveryOrder" ThisKey="DeliveryOrderId" OtherKey="Id" Type="DeliveryOrder" IsForeignKey="true" />
      <Association Name="Product_DeliveryOrderDetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="ProductStorage_DeliveryOrderDetail" Member="ProductStorage" ThisKey="ProductStorageId" OtherKey="Id" Type="ProductStorage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImportProfiles" Member="ImportProfiles">
    <Type Name="ImportProfile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Target" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Company_ImportProfile" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssignedDeliveryOrderDetails" Member="AssignedDeliveryOrderDetails">
    <Type Name="AssignedDeliveryOrderDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeliveryOrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductStorageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LotsNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InputInvoice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentProductNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StorageArea" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSucess" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DeliveryOrder_AssignedDeliveryOrderDetail" Member="DeliveryOrder" ThisKey="DeliveryOrderId" OtherKey="Id" Type="DeliveryOrder" IsForeignKey="true" />
      <Association Name="Product_AssignedDeliveryOrderDetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="ProductStorage_AssignedDeliveryOrderDetail" Member="ProductStorage" ThisKey="ProductStorageId" OtherKey="Id" Type="ProductStorage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_ProductStorages" Member="View_ProductStorages">
    <Type Name="View_ProductStorage">
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductChName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductEngName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductNumber1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductNumber2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentProductNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OriginalCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsableCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="LotsNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Spec" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BarCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SecurityCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StorageAreas" Member="StorageAreas">
    <Type Name="StorageArea">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="库位编号" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="备注" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StorageRackId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StorageArea_ProductStorage" Member="ProductStorages" ThisKey="Id" OtherKey="AreaId" Type="ProductStorage" />
      <Association Name="StorageRack_StorageArea" Member="StorageRack" ThisKey="StorageRackId" OtherKey="id" Type="StorageRack" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductStorages" Member="ProductStorages">
    <Type Name="ProductStorage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InputDetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentProductNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OriginalCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsableCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LotsNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductStorage_DeliveryOrderDetail" Member="DeliveryOrderDetails" ThisKey="Id" OtherKey="ProductStorageId" Type="DeliveryOrderDetail" />
      <Association Name="ProductStorage_AssignedDeliveryOrderDetail" Member="AssignedDeliveryOrderDetails" ThisKey="Id" OtherKey="ProductStorageId" Type="AssignedDeliveryOrderDetail" />
      <Association Name="Company_ProductStorage" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
      <Association Name="Product_ProductStorage" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="StorageArea_ProductStorage" Member="StorageArea" ThisKey="AreaId" OtherKey="Id" Type="StorageArea" IsForeignKey="true" />
      <Association Name="InputOrderDetail_ProductStorage" Member="InputOrderDetail" ThisKey="InputDetailId" OtherKey="ID" Type="InputOrderDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RackArea" Member="RackAreas">
    <Type Name="RackArea">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AreaType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="RackArea_StorageRack" Member="StorageRacks" ThisKey="id" OtherKey="RackAreaID" Type="StorageRack" />
    </Type>
  </Table>
  <Table Name="dbo.RackType" Member="RackTypes">
    <Type Name="RackType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="RackType_StorageRack" Member="StorageRacks" ThisKey="id" OtherKey="RackTypeID" Type="StorageRack" />
    </Type>
  </Table>
  <Table Name="dbo.StorageRacks" Member="StorageRacks">
    <Type Name="StorageRack">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RackName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RackTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RackAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StorageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StorageRack_StorageArea" Member="StorageAreas" ThisKey="id" OtherKey="StorageRackId" Type="StorageArea" />
      <Association Name="RackArea_StorageRack" Member="RackArea" ThisKey="RackAreaID" OtherKey="id" Type="RackArea" IsForeignKey="true" />
      <Association Name="RackType_StorageRack" Member="RackType" ThisKey="RackTypeID" OtherKey="id" Type="RackType" IsForeignKey="true" />
      <Association Name="Storage_StorageRack" Member="Storage" ThisKey="StorageID" OtherKey="Id" Type="Storage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Storages" Member="Storages">
    <Type Name="Storage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="仓库编号" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="仓库名称" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="仓库地址" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="备注" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Storage_StorageRack" Member="StorageRacks" ThisKey="Id" OtherKey="StorageID" Type="StorageRack" />
    </Type>
  </Table>
  <Table Name="dbo.InputOrders" Member="InputOrders">
    <Type Name="InputOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InputOrderNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FromWhere" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreInputDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EnterDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EnterUser" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnterConfirmUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="InputOrder_InputOrderDetail" Member="InputOrderDetails" ThisKey="ID" OtherKey="InputOrderId" Type="InputOrderDetail" />
      <Association Name="Company_InputOrder" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InputOrderDetails" Member="InputOrderDetails">
    <Type Name="InputOrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InputOrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentProductNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StorageAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InputCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LotsNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="InputOrderDetail_ProductStorage" Member="ProductStorages" ThisKey="ID" OtherKey="InputDetailId" Type="ProductStorage" />
      <Association Name="Company_InputOrderDetail" Member="Company" ThisKey="CompanyId" OtherKey="Id" Type="Company" IsForeignKey="true" />
      <Association Name="InputOrder_InputOrderDetail" Member="InputOrder" ThisKey="InputOrderId" OtherKey="ID" Type="InputOrder" IsForeignKey="true" />
      <Association Name="Product_InputOrderDetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>